"use client";
import { Inter } from "next/font/google";
import "./globals.css";

import { QueryClientProvider, QueryClient } from "@tanstack/react-query";

import Navbar from "@/app/common/Navbar";
import Footer from "./common/Footer";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <Navbar />
          {children}
          <Footer />
        </QueryClientProvider>
      </body>
    </html>
  );
}
