"use client";
import { Inter } from "next/font/google";
import "./globals.css";

import { QueryClientProvider, QueryClient } from "@tanstack/react-query";

import Footer from "./common/Footer";
import Navbar from "./common/Navbar";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <div className="sm:bg-gray-50 z-50 sm:w-full sm:fixed sm:top-0 sm:left-0">
            <Navbar />
          </div>
          {children}
          <Footer />
        </QueryClientProvider>
      </body>
    </html>
  );
}
